// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLineELB

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_TestBatteryVoltage;
extern lv_obj_t * ui_TBVvalue;
extern lv_obj_t * ui_TestBatteryCurrent;
extern lv_obj_t * ui_TBCvalue;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Chart6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_Pvalue;
extern lv_obj_t * ui_Current;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_AuxillaryBattery;
extern lv_obj_t * ui_ABvalue;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Potentiometer;
extern lv_obj_t * ui_Potvalue;
extern lv_obj_t * ui_Temperatures;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_HeatsinkTemp;
extern lv_obj_t * ui_HSTvalue;
extern lv_obj_t * ui_TestBatteryTemp;
extern lv_obj_t * ui_TBTvalue;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_File_Storage;
extern lv_obj_t * ui_SDReminder;
extern lv_obj_t * ui_SDCardStatus;
extern lv_obj_t * ui_ExportStatus;
extern lv_obj_t * ui_File_Name;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Keyboard3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_TabView1;
extern lv_obj_t * uic_Current;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

