// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLineELB

#include "../ui.h"

// COMPONENT Container1

lv_obj_t * ui_Container1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container1;
    cui_Container1 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container1);
    lv_obj_set_width(cui_Container1, 789);
    lv_obj_set_height(cui_Container1, 447);
    lv_obj_set_align(cui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Chart4;
    cui_Chart4 = lv_chart_create(cui_Container1);
    lv_obj_set_width(cui_Chart4, 650);
    lv_obj_set_height(cui_Chart4, 100);
    lv_obj_set_x(cui_Chart4, 70);
    lv_obj_set_y(cui_Chart4, 50);
    lv_chart_set_type(cui_Chart4, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(cui_Chart4, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(cui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(cui_Chart4, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * cui_Chart4_series_1 = lv_chart_add_series(cui_Chart4, lv_color_hex(0x808080),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t cui_Chart4_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(cui_Chart4, cui_Chart4_series_1, cui_Chart4_series_1_array);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER1_NUM);
    children[UI_COMP_CONTAINER1_CONTAINER1] = cui_Container1;
    children[UI_COMP_CONTAINER1_CHART4] = cui_Chart4;
    lv_obj_add_event_cb(cui_Container1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container1_create_hook(cui_Container1);
    return cui_Container1;
}

